# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"t\n\rCreateRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1e\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.book.GenreType\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\"-\n\x0b\x43reateReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"(\n\nGetRequest\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_ISBN\"*\n\x08GetReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"\xbf\x01\n\x04\x42ook\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12#\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.book.GenreTypeH\x03\x88\x01\x01\x12\x1b\n\x0epublishingYear\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x07\n\x05_ISBNB\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x11\n\x0f_publishingYear\"k\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\t\x12\x1b\n\x05\x61\x42ook\x18\x02 \x01(\x0b\x32\n.book.BookH\x00\x12\x1c\n\x06status\x18\x03 \x01(\x0e\x32\x0c.book.StatusB\x06\n\x04\x62ook*2\n\tGenreType\x12\x0b\n\x07\x46ICTION\x10\x00\x12\x0b\n\x07\x46\x41NTASY\x10\x01\x12\x0b\n\x07ROMANCE\x10\x02*\"\n\x06Status\x12\r\n\tavailable\x10\x00\x12\t\n\x05taken\x10\x01\x32y\n\x10InventoryService\x12\x36\n\nCreateBook\x12\x13.book.CreateRequest\x1a\x11.book.CreateReply\"\x00\x12-\n\x07GetBook\x12\x10.book.GetRequest\x1a\x0e.book.GetReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\003HLW'
  _GENRETYPE._serialized_start=574
  _GENRETYPE._serialized_end=624
  _STATUS._serialized_start=626
  _STATUS._serialized_end=660
  _CREATEREQUEST._serialized_start=20
  _CREATEREQUEST._serialized_end=136
  _CREATEREPLY._serialized_start=138
  _CREATEREPLY._serialized_end=183
  _GETREQUEST._serialized_start=185
  _GETREQUEST._serialized_end=225
  _GETREPLY._serialized_start=227
  _GETREPLY._serialized_end=269
  _BOOK._serialized_start=272
  _BOOK._serialized_end=463
  _INVENTORYITEM._serialized_start=465
  _INVENTORYITEM._serialized_end=572
  _INVENTORYSERVICE._serialized_start=662
  _INVENTORYSERVICE._serialized_end=783
# @@protoc_insertion_point(module_scope)
